---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(sf)
library(lubridate)
library(move)
library(here)
library(amt)
```

```{r}
amwo_data <- getMovebankData(study = "American Woodcock Migration Ecology in Eastern North America", 
                             login = readRDS("movebank_credentials.rds"), 
                             removeDuplicatedTimestamps=TRUE)
amwo_data <- as.data.frame(amwo_data)

amwo_data %>%
  transmute(ID = local_identifier,
            time = as.character(timestamp),
            lon = location_long, 
            lat = location_lat,
            event_id = event_id,
            tagtype = comments,
            sex = sex,
            age = taxon_detail,
            height_above_wgs84 = height_above_msl,
            fix = location_error_text,
            point_state = behavioural_classification) ->
  amwo_data
```

Delineate skips here (need to do it before I start filtering)
```{r}
amwo_nested <- amwo_data %>% 
  nest(.by = ID)

amwo_nested$track <- map(amwo_nested$data, function(x){ #remember to transform to 5070
  a <- mk_track(x, .x = lon, .y = lat, crs = 4326, all_cols = TRUE) %>% 
    transform_coords(5070)
  a$sl <- step_lengths(a)
  return(a)
})

amwo_nested$track <- map(amwo_nested$track, function(x){
  x$moving <- NA
  for(i in 1:nrow(x)){ # if it's the first row, the bird isn't moving
    if(i == 1){
      x$moving[i] <- FALSE
    } else if(i == nrow(x)){ # if it's the last row, the bird isn't moving
      x$moving[i] <- FALSE
    } else {
      if(x$sl[i-1] >= 1000 & x$sl[i] >= 1000){ #if the current and prior steps are both at least 1 km, the bird is moving
        x$moving[i] <- TRUE
      } else {
        x$moving[i] <- FALSE
      }
    }
  }
  return(x)
})

amwo_nested <- amwo_nested %>% 
  dplyr::select(ID, track) %>% 
  unnest(cols = c(track)) %>% 
  dplyr::select(event_id, moving)

amwo_data <- amwo_data %>% 
  left_join(amwo_nested)

any(is.na(amwo_data$moving))# should be false

amwo_data$moving %>% 
  table()
```

Is a location overwater?
```{r}
amwo_sf <- amwo_data %>% 
  st_as_sf(coords = c("lon", "lat"), crs = 4326, remove = FALSE)

coastline_polygon <- st_read("D:/OneDrive - University of Maine System/MaineAnalysis/Data/coastline/ne_10m_coastline_poly.shp") %>% 
  st_transform(4326) %>% 
  transmute(on_land = TRUE)

amwo_sf <- amwo_sf %>% 
  st_join(coastline_polygon)

# As the coastline isn't perfect, I have some exceptions here that I'll set to on land
overwater_exceptions <- read.csv(here("overwater_exceptions.csv"))

amwo_sf <- amwo_sf %>%
  mutate(on_land = if_else(event_id %in% overwater_exceptions$event_id, TRUE, on_land))

# set na values to FALSE (ie onland == FALSE is an overwater location)
amwo_sf <- amwo_sf %>%
  mutate(on_land = if_else(is.na(on_land), FALSE, on_land))

# count the number of overwater locations
amwo_sf %>% 
  st_drop_geometry() %>% 
  group_by(on_land) %>% 
  tally()

# map the overwater locations: good for proofing the locations
# amwo_sf %>% 
#   filter(on_land == FALSE) %>% 
#   mapview::mapview()

```


Save for later use
```{r}
amwo_data$on_land <- amwo_sf$on_land

amwo_data %>%
  filter((!is.na(height_above_wgs84)) & (!is.na(point_state))) %>%
  write.csv(here("intermediate_files", "imported_movebank_data.csv"))

# Vertical datum is WKID::115700
```

