---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(jagsUI)
library(here)
library(furrr)
library(bayestestR)
library(truncnorm)
```

```{r}
original_results <- readRDS(here("bayesian_modeling", "gamma_original_stan.rds"))
new_results <- readRDS(here("bayesian_modeling", "gamma_original_stan2.rds"))
```

mu_bias
```{r}
mu_bias_old <- tibble(type = "old", 
                            samples = rstan::extract(original_results, "mu_bias")[[1]])

mu_bias_new <- tibble(type = "new", 
                            samples = rstan::extract(new_results, "mu_bias")[[1]])
  
mu_bias <- bind_rows(mu_bias_old, mu_bias_new)

ggplot(data = mu_bias, mapping = aes(x = samples, color = type)) +
  geom_density() +
  theme_bw()
```

sigma_error
```{r}
sigma_error_old <- tibble(type = "old", 
                            samples = rstan::extract(original_results, "sigma_error")[[1]])

sigma_error_new <- tibble(type = "new", 
                            samples = rstan::extract(new_results, "sigma_error")[[1]])
  
sigma_error <- bind_rows(sigma_error_old, sigma_error_new)

ggplot(data = sigma_error, mapping = aes(x = samples, color = type)) +
  geom_density() +
  theme_bw()
```

shape
```{r}
shape_old <- tibble(type = "old", 
                            samples = rstan::extract(original_results, "shape")[[1]])

shape_new <- tibble(type = "new", 
                            samples = rstan::extract(new_results, "shape")[[1]])
  
shape <- bind_rows(shape_old, shape_new)

ggplot(data = shape, mapping = aes(x = samples, color = type)) +
  geom_density() +
  theme_bw()
```

rate
```{r}
rate_old <- tibble(type = "old", 
                            samples = rstan::extract(original_results, "rate")[[1]])

rate_new <- tibble(type = "new", 
                            samples = rstan::extract(new_results, "rate")[[1]])
  
rate <- bind_rows(rate_old, rate_new)

ggplot(data = rate, mapping = aes(x = samples, color = type)) +
  geom_density() +
  theme_bw()
```

new sample size vs prior
```{r}
sample_size_posterior <- tibble(type = "posterior", 
                            samples = rstan::extract(new_results, "sample_size")[[1]]/428)

sample_size_prior <- tibble(type = "prior", 
                            samples = runif(n = 30000, min = 0, max = 1))

sample_size <- bind_rows(sample_size_prior, sample_size_posterior)

ggplot(data = sample_size, mapping = aes(x = samples, color = type)) +
  geom_density() +
  theme_bw()# +
  #geom_vline(xintercept = 0.33, color = "blue")
```


